### ISSUE TITLE
Cannot parse gatling.jvmArgs properly

### ISSUE THREAD

**Issue by rvansa** [gatling/gatling-maven#6] opened 2016-02-02 10:34 UTC
I am trying to debug my custom code integration in gatling, executing the scenario through

```
mvn gatling:execute -Dgatling.jvmArgs="agentlib:jdwp=address=5005,transport=dt_socket,server=y,suspend=y"
```

However this is not parsed properly; it seems that only the first argument (address=5005) goes in and the rest is lost, therefore I get

```
ERROR: JDWP address specified without transport: -agentlib:jdwp=address=5005
```

It would be even more convenient if there was option to run gatling from within Maven's JVM, since that would allow one-click IDE (Intellij IDEA in my case) debugging.

**Comment by rvansa** [comment] 2016-02-02 12:33
It is a problem of parsing in Maven, not really in this plugin - since the jvmArgs is declared as `List<String>`, it's Maven who tries to parse it (split by commas). It is possible to add the debugging argument into pom.xml, but that's not really convenient. The plugin should offer simple String argument that wouldn't be (mis)interpreted.

**Comment by slandelle** [comment] 2016-02-02 12:52
> The plugin should offer simple String argument that wouldn't be (mis)interpreted.

Well, it looks like a maven issue that should be reported to the maven project.

> The plugin should offer simple String argument that wouldn't be (mis)interpreted.

Maybe, but not at the cost of introducing crappy code to compensate for an upstream issue. Contributions welcome.

Gatling runs in a forked JVM so it can have different JVM tunings and a different classpath than maven.

There's also other ways to attach the debugger, like attaching on the pid, or using our maven archetype and use the main class launcher.

**Comment by rvansa** [comment] 2016-02-02 13:38
It's rather a Maven feature than a bug - the default behaviour (splitting by commas) probably works in most cases.

I have not suggested any 'crappy code' - or do you speak about the proposal to have all args in single argument?

I see that non-forked run is not really desired - fair enough.

Attaching on the PID does not allow you to suspend before the debugger is attached. Archetype seems like a viable option, too, thanks for the hint.

**Comment by slandelle** [comment] 2016-02-02 13:51
> It's rather a Maven feature than a bug - the default behaviour (splitting by commas) probably works in most cases.

Not a bug, but a possible limitation. In your case, it would be great if maven could provide a way to escape some block, like using a delimiter.

> I have not suggested any 'crappy code' - or do you speak about the proposal to have all args in single argument?

Sorry, I meant that adding some weird code to support such a specific case for which there's several workaround would be a no go. Implementation would have to be clean.

> Attaching on the PID does not allow you to suspend before the debugger is attached.

Yes, you'd have to add a Thread.sleep in your simulation so you have time to attach.

> Archetype seems like a viable option

It is. That's usually what I do.

Closing for now. Feel free to reopen if you come up with an elegant solution you want to contribute.

**Closed by slandelle** 2016-02-02 13:51 UTC
